services:
  backend:
    build: .
    container_name: backend-postgres
    ports:
      - "8083:8081"  # map cổng local 8083 -> container 8080
    network_mode: bridge  # container có internet outbound
