spring.application.name=backend

server.port=8083

# Database (Railway)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret-key=${JWT_SECRET_KEY_BASE64}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
