# ================= SERVER =================
spring.application.name=backend
server.port=${PORT:8080}

# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://dpg-d49k9395pdvs73cvfn90-a.oregon-postgres.render.com/backend_db_mru8?sslmode=require
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ================= JPA / HIBERNATE =================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= JWT =================
jwt.secret-key=${JWT_SECRET_KEY_BASE64}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
